### ISSUE TITLE
Django 1.10 compatibility

### ISSUE THREAD

**Issue by zsiciarz** [pydanny/dj-pagination#1]
Hi Daniel! Good to see someone actively maintaining my go-to pagination package. One thing I've noticed - `dj-pagination` isn't yet compatible with 1.10, raising the following error:

`TypeError: render_to_string() got an unexpected keyword argument 'context_instance'`

which is expected since 1.10 removed that kwarg. I've [sent a PR](https://github.com/zyga/django-pagination/pull/40) to zyga's repo, unfortunately it looks like it isn't maintained anymore. 
I see you've already cleaned up Travis config, so how do you feel about code changes for 1.10? Do you want me to send a similar (but shorter) PR here?

**Comment by pydanny** [comment]
I would love a 1.10 pull request. :)

**Comment by zsiciarz** [comment]
Well, here it is: https://github.com/pydanny/dj-pagination/pull/2.

**Comment by pydanny** [comment]
Apologies for the VERY slow response. I merged in your PR and did a release on PyPI: Released! https://pypi.python.org/pypi/dj-pagination

Thanks so much!

**Comment by zsiciarz** [comment]
No worries :) Thanks for the release!
