### ISSUE TITLE
Release 2.3.1 reverts change from #14

### ISSUE THREAD

**Issue by bdruth** [pydanny/dj-pagination#19]
Left comment here - https://github.com/pydanny/dj-pagination/issues/15#issuecomment-354525282 -- looks like something didn't merge/commit right for the 2.3.1 release - this breaks all installs that use dj-pagination as of the release of Django-2.

**Comment by jmichalicek** [comment]
If I get 5 minutes free, I'm happy to just update and make the PR again.  It's not like it's a lot of work to redo.

**Comment by pydanny** [comment]
Please do. Thanks! :)

**Comment by jlward** [comment]
+1

Just ran into this. Please let me know if I can help get this fixed sooner rather than later.

**Comment by jlward** [comment]
For anyone else running into this, we are installing from `git+git://github.com/pydanny/dj-pagination.git@e491c8c89151c6713e0b2eb46703b8ee63be4f02#egg=dj-pagination` in the mean time.

**Comment by jmichalicek** [comment]
I just made #20 which should put things back

**Comment by pydanny** [comment]
@jmichalicek Just released 2.3.2 on PyPI.
