### ISSUE TITLE
When PAGINATION_DISABLE_LINK_FOR_FIRST_PAGE is True, the page 1 url links to the current page.

### ISSUE THREAD

**Issue by christianmlong** [pydanny/dj-pagination#6]
When PAGINATION_DISABLE_LINK_FOR_FIRST_PAGE is True, the href for the anchor tag for the number 1 page is blank. What this means is, when you click on the number 1, you just stay on the current page instead of going to page 1.

Look at this snippet of generated html. We are on page 4. If you hover over the number 1, the tooltip will show /current/path/?page=4. And, if you click on the number 1, nothing happens. You stay on the current page.

```
<div class="pagination">
  <a href="?page=3" class="prev">‹‹ previous</a>
  <a href="" class="page">1</a>
  <a href="?page=2" class="page">2</a>
  <a href="?page=3" class="page">3</a>
  <span class="current page">4</span>
  <a href="?page=5" class="page">5</a>
  <a href="?page=6" class="page">6</a>
  ...
  <a href="?page=8585" class="page">8585</a>
  <a href="?page=8586" class="page">8586</a>
  <a href="?page=5" class="next">next ››</a>
</div>
```

The problem is, the href for page 1 is blank. I think the bug is [here](https://github.com/pydanny/dj-pagination/blob/master/dj_pagination/templates/pagination/pagination.html#L25), on line 25 of [pagination.html](https://github.com/pydanny/dj-pagination/blob/master/dj_pagination/templates/pagination/pagination.html).

```
{% if disable_link_for_first_page and page == 1 %}
<a href="{{ request.path }}{% if getvars %}?{{ getvars|slice:"1:" }}{% endif %}" class="page">{{ page }}</a>
```

I think there is another instance of the same problem on [line 7](https://github.com/pydanny/dj-pagination/blob/master/dj_pagination/templates/pagination/pagination.html#L7) of pagination.html. When you are on page 2, the href for the anchor for the word "previous" is also blank. So if you are on page 2, and you click "previous", you stay on page 2.

**Comment by christianmlong** [comment]
Django 1.10.6, dj-pagination 2.2.1

My template configuration
```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
       'DIRS': [
            SITE_TEMPLATES_DIR,
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```

**Comment by pydanny** [comment]
If you submit a pull request I'll create a new PyPI release. 😄

**Comment by chengxiao** [comment]
Same problem with @christianmlong 
how to fix it?

**Comment by christianmlong** [comment]
I ended up just using PAGINATION_DISABLE_LINK_FOR_FIRST_PAGE=False. The urls aren't as clean, but it works.

**Comment by strogonoff** [comment]
I believe the problem is that {{ request.path }} is empty on lines 7 and 25 because {{ request }} does not get passed to the pagination template. Pull request pending. I’m using my fork in the meantime and not experiencing this issue anymore.

**Comment by pydanny** [comment]
Pushed version 2.3 to PyPI: https://pypi.python.org/pypi/dj-pagination
