### ISSUE TITLE
previous issue

### ISSUE THREAD

**Issue by yingshang** [pydanny/dj-pagination#8]
I'll make a video of the problem and you can see it
`https://youtu.be/1UlJlZWUcyM`
when i next page is success,but i previous page 1 is wrong,i can't previous page 1,only previous page 2
how can i fix that?
thanks

**Comment by chengxiao** [comment]
same problem with @yingshang 
兄弟 你解决了么?

**Comment by City-Zero** [comment]
同，@chengxiao
求解Django1.11怎么用，直接提示"You need to enable 'django.core.context_processors.request'."，
把作者说的加进去又说没那个模块...

**Comment by pydanny** [comment]
Does this problem remain? Does @City-Zero's fix of `django.core.context_processors.request` the issue?

**Comment by pydanny** [comment]
Since it's been a few months without comment, I'm closing this issue.
